<?php
session_start();
require_once '../config/db.php';

if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'Registrar') {
  header("Location: login.php");
  exit;
}

// === FILTER INPUTS ===
$filter_status = $_GET['status'] ?? '';
$filter_start  = $_GET['start_date'] ?? '';
$filter_end    = $_GET['end_date'] ?? '';

// === BASE QUERY ===
$sql = "
  SELECT i.batch_id, i.imported_by, i.total_students, i.import_time,
         b.total_certificates, b.generated_by, b.generated_at
  FROM import_logs i
  LEFT JOIN batch_reports b ON i.batch_id = b.batch_id
  WHERE 1=1
";

// === APPLY FILTERS ===
$params = [];
if ($filter_status === 'generated') {
  $sql .= " AND b.total_certificates IS NOT NULL";
} elseif ($filter_status === 'not_generated') {
  $sql .= " AND b.total_certificates IS NULL";
}

if ($filter_start && $filter_end) {
  $sql .= " AND DATE(i.import_time) BETWEEN ? AND ?";
  $params[] = $filter_start;
  $params[] = $filter_end;
}

$sql .= " ORDER BY i.import_time DESC";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$batches = $stmt->fetchAll();

// === SUMMARY STATS ===
$total_imports = count($batches);
$total_students = array_sum(array_column($batches, 'total_students'));
$total_certs = array_sum(array_map(fn($b) => (int)($b['total_certificates'] ?? 0), $batches));
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Registrar Batch Reports</title>
  <link rel="stylesheet" href="../assets/css/bootstrap.min.css">
  <style>
    body { background: #f8f9fa; }
    .summary-card { border-left: 5px solid #0d6efd; }
    .table thead th { background: #0d6efd; color: white; }
    .btn-sm { font-size: 13px; padding: 4px 8px; }
  </style>
</head>
<body class="p-4">
<div class="container">
  <h3 class="mb-3 text-primary">📦 Registrar Batch Reports</h3>
  <p class="text-muted">Filter and view details of all imported and generated certificate batches.</p>

  <!-- === SUMMARY CARDS === -->
  <div class="row mb-4">
    <div class="col-md-4">
      <div class="card summary-card shadow-sm p-3">
        <h5>Total Batches</h5>
        <h3><?= $total_imports; ?></h3>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card summary-card shadow-sm p-3 border-success">
        <h5>Total Students Imported</h5>
        <h3><?= $total_students; ?></h3>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card summary-card shadow-sm p-3 border-warning">
        <h5>Total Certificates Generated</h5>
        <h3><?= $total_certs; ?></h3>
      </div>
    </div>
  </div>

  <!-- === FILTER FORM === -->
  <form class="row g-3 mb-4" method="GET">
    <div class="col-md-3">
      <label class="form-label">Status</label>
      <select name="status" class="form-select">
        <option value="">All</option>
        <option value="generated" <?= $filter_status === 'generated' ? 'selected' : ''; ?>>Generated</option>
        <option value="not_generated" <?= $filter_status === 'not_generated' ? 'selected' : ''; ?>>Not Generated</option>
      </select>
    </div>
    <div class="col-md-3">
      <label class="form-label">From</label>
      <input type="date" name="start_date" value="<?= htmlspecialchars($filter_start); ?>" class="form-control">
    </div>
    <div class="col-md-3">
      <label class="form-label">To</label>
      <input type="date" name="end_date" value="<?= htmlspecialchars($filter_end); ?>" class="form-control">
    </div>
    <div class="col-md-3 d-flex align-items-end">
      <button class="btn btn-primary w-100">🔍 Apply Filters</button>
    </div>
  </form>

  <!-- === TABLE === -->
  <div class="card shadow-sm">
    <div class="card-body p-0">
      <table class="table table-striped table-hover mb-0">
        <thead>
          <tr>
            <th>Batch ID</th>
            <th>Imported By</th>
            <th>Total Students</th>
            <th>Import Time</th>
            <th>Total Certificates</th>
            <th>Generated By</th>
            <th>Generated At</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <?php if ($batches): foreach ($batches as $b): ?>
          <tr>
            <td><?= htmlspecialchars($b['batch_id']); ?></td>
            <td><?= htmlspecialchars($b['imported_by']); ?></td>
            <td><?= htmlspecialchars($b['total_students']); ?></td>
            <td><?= htmlspecialchars($b['import_time']); ?></td>
            <td><?= $b['total_certificates'] ?? '—'; ?></td>
            <td><?= htmlspecialchars($b['generated_by'] ?? '—'); ?></td>
            <td><?= htmlspecialchars($b['generated_at'] ?? '—'); ?></td>
            <td>
              <?php
              // Detect PDF and ZIP by batch ID or timestamp pattern
              $batchPdf = "../certificates/pdfs/Batch_Certificates_{$b['batch_id']}.pdf";
              $batchZip = "../certificates/pdfs/Batch_{$b['batch_id']}.zip";

              if (!file_exists($batchPdf)) {
                $patternPdf = glob("../certificates/pdfs/Batch_Certificates_{$b['batch_id']}*.pdf");
                if (!empty($patternPdf)) $batchPdf = $patternPdf[0];
              }
              if (!file_exists($batchZip)) {
                $patternZip = glob("../certificates/pdfs/Batch_{$b['batch_id']}*.zip");
                if (!empty($patternZip)) $batchZip = $patternZip[0];
              }
              ?>

              <?php if (file_exists($batchPdf)): ?>
                <a href="<?= $batchPdf; ?>" target="_blank" class="btn btn-sm btn-warning">📄 View PDF</a>
              <?php endif; ?>

              <?php if (file_exists($batchZip)): ?>
                <a href="<?= $batchZip; ?>" class="btn btn-sm btn-success">⬇ Download ZIP</a>
              <?php endif; ?>

              <?php if (!file_exists($batchPdf) && !file_exists($batchZip)): ?>
                <span class="text-muted small">No files yet</span>
              <?php endif; ?>
            </td>
          </tr>
        <?php endforeach; else: ?>
          <tr><td colspan="8" class="text-center text-muted">No batches found for the selected filters.</td></tr>
        <?php endif; ?>
        </tbody>
      </table>
    </div>
  </div>

  <a href="dashboard.php" class="btn btn-secondary mt-4">⬅ Back to Dashboard</a>
</div>
</body>
</html>
